import type { BlueprintResult } from '../core';

/**
 * Generates dbdiagram.io compatible code from a BlueprintResult
 * Format: https://dbdiagram.io/d
 */
export function generateDbDiagramCode(result: BlueprintResult): string {
  const lines: string[] = [];

  // Add header comment
  lines.push('// Generated by Power Platform Solution Blueprint (PPSB)');
  lines.push(`// ${result.metadata.generatedAt}`);
  lines.push('// Paste this code at https://dbdiagram.io/d to visualize');
  lines.push('');

  // Track processed relationships to avoid duplicates
  const processedRelationships = new Set<string>();

  // Process each entity
  for (const entityBlueprint of result.entities) {
    const entity = entityBlueprint.entity;
    const tableName = entity.LogicalName;

    lines.push(`Table ${tableName} {`);

    // Add table note with display name
    const displayName = entity.DisplayName?.UserLocalizedLabel?.Label || tableName;
    lines.push(`  Note: '${displayName}'`);
    lines.push('');

    // Add attributes
    const attributes = entity.Attributes || [];
    for (const attr of attributes) {
      const columnName = attr.LogicalName;
      const dataType = mapAttributeTypeToDbType(attr.AttributeType);
      const constraints: string[] = [];

      // Primary key
      if (attr.IsPrimaryId) {
        constraints.push('pk');
      }

      // Required field
      if (attr.RequiredLevel?.Value === 'ApplicationRequired' || attr.RequiredLevel?.Value === 'SystemRequired') {
        constraints.push('not null');
      }

      // Add note with display name
      const attrDisplayName = attr.DisplayName?.UserLocalizedLabel?.Label;
      if (attrDisplayName && attrDisplayName !== columnName) {
        constraints.push(`note: '${attrDisplayName.replace(/'/g, "\\'")}'`);
      }

      const constraintStr = constraints.length > 0 ? ` [${constraints.join(', ')}]` : '';
      lines.push(`  ${columnName} ${dataType}${constraintStr}`);
    }

    lines.push('}');
    lines.push('');
  }

  // Process relationships
  lines.push('// Relationships');
  lines.push('');

  for (const entityBlueprint of result.entities) {
    const entity = entityBlueprint.entity;

    // Many-to-One relationships (this entity references another)
    const manyToOneRels = entity.ManyToOneRelationships || [];
    for (const rel of manyToOneRels) {
      const relKey = `${rel.ReferencingEntity}.${rel.ReferencingAttribute}->${rel.ReferencedEntity}.${rel.ReferencedAttribute}`;
      if (!processedRelationships.has(relKey)) {
        processedRelationships.add(relKey);
        // Many-to-one: ReferencingEntity.ReferencingAttribute > ReferencedEntity.ReferencedAttribute
        lines.push(`Ref: ${rel.ReferencingEntity}.${rel.ReferencingAttribute} > ${rel.ReferencedEntity}.${rel.ReferencedAttribute}`);
      }
    }

    // Many-to-Many relationships
    const manyToManyRels = entity.ManyToManyRelationships || [];
    for (const rel of manyToManyRels) {
      // Create a relationship key to avoid duplicates (both entities will have this relationship)
      const entities = [rel.Entity1LogicalName, rel.Entity2LogicalName].sort();
      const relKey = `${entities[0]}<>${entities[1]}:${rel.IntersectEntityName}`;

      if (!processedRelationships.has(relKey)) {
        processedRelationships.add(relKey);
        // Many-to-many: Entity1 <> Entity2
        lines.push(`Ref: ${rel.Entity1LogicalName}.${entity.PrimaryIdAttribute} <> ${rel.Entity2LogicalName}.${entity.PrimaryIdAttribute} [note: 'via ${rel.IntersectEntityName}']`);
      }
    }
  }

  return lines.join('\n');
}

/**
 * Maps Dataverse attribute types to database column types for dbdiagram.io
 */
function mapAttributeTypeToDbType(attributeType: string): string {
  const typeMap: Record<string, string> = {
    'String': 'nvarchar',
    'Memo': 'nvarchar(max)',
    'Integer': 'int',
    'BigInt': 'bigint',
    'Decimal': 'decimal',
    'Double': 'float',
    'Money': 'money',
    'Boolean': 'bit',
    'DateTime': 'datetime',
    'Lookup': 'uniqueidentifier',
    'Customer': 'uniqueidentifier',
    'Owner': 'uniqueidentifier',
    'Uniqueidentifier': 'uniqueidentifier',
    'Picklist': 'int',
    'State': 'int',
    'Status': 'int',
    'Virtual': 'nvarchar',
    'EntityName': 'nvarchar',
    'ManagedProperty': 'bit',
  };

  return typeMap[attributeType] || 'nvarchar';
}
