import type { BlueprintResult } from '../core';
import { isSystemEntity, isSystemRelationship } from './systemFilters.js';

/**
 * Generates dbdiagram.io compatible code from a BlueprintResult
 * Format: https://dbdiagram.io/d
 */
export function generateDbDiagramCode(result: BlueprintResult): string {
  const lines: string[] = [];

  // Add header comment
  lines.push('// Generated by Power Platform Solution Blueprint (PPSB)');
  lines.push(`// ${result.metadata.generatedAt}`);
  lines.push('// Paste this code at https://dbdiagram.io/d to visualize');
  lines.push('');

  // Track processed relationships to avoid duplicates
  const processedRelationships = new Set<string>();

  // ── Pass 1: build exportedEntities + entityAttributes ───────────────────
  // All non-system entities go into exportedEntities so their relationships
  // are always emitted.  entityAttributes is only populated for entities that
  // have real attribute data; absence means "not yet discovered".
  const exportedEntities = new Set<string>();
  const entityAttributes = new Map<string, Set<string>>();

  for (const entityBlueprint of result.entities) {
    const tableName = entityBlueprint.entity.LogicalName.toLowerCase();
    if (!isSystemEntity(tableName)) {
      exportedEntities.add(tableName);
      const attrs = entityBlueprint.entity.Attributes || [];
      if (attrs.length > 0) {
        const attrSet = new Set<string>();
        for (const attr of attrs) {
          attrSet.add(attr.LogicalName.toLowerCase());
        }
        entityAttributes.set(tableName, attrSet);
      }
    }
  }

  // ── Pass 2: derive columns from relationship data for attribute-less entities ─
  // For every entity that has no discovered attributes, we collect the column
  // names that ManyToOne relationships reference on it.  This ensures the
  // Table block contains exactly the columns that appear in Ref lines, so
  // dbdiagram.io never sees "Column X does not exist in Table Y".
  const relationshipColumns = new Map<string, Set<string>>();

  for (const entityBlueprint of result.entities) {
    for (const rel of entityBlueprint.entity.ManyToOneRelationships || []) {
      if (isSystemRelationship(rel.SchemaName, rel.ReferencingAttribute, rel.ReferencedEntity, rel.ReferencingEntity)) {
        continue;
      }

      const referencingName = rel.ReferencingEntity.toLowerCase();
      const referencedName  = rel.ReferencedEntity.toLowerCase();

      if (!exportedEntities.has(referencingName) || !exportedEntities.has(referencedName)) {
        continue;
      }

      // Only collect relationship-derived columns for entities that have no
      // real attribute data — entities with attributes use their own column list.
      if (!entityAttributes.has(referencingName)) {
        if (!relationshipColumns.has(referencingName)) {
          relationshipColumns.set(referencingName, new Set());
        }
        relationshipColumns.get(referencingName)!.add(rel.ReferencingAttribute.toLowerCase());
      }

      if (!entityAttributes.has(referencedName)) {
        if (!relationshipColumns.has(referencedName)) {
          relationshipColumns.set(referencedName, new Set());
        }
        relationshipColumns.get(referencedName)!.add(rel.ReferencedAttribute.toLowerCase());
      }
    }
  }

  // ── Pass 3: generate Table blocks ───────────────────────────────────────
  for (const entityBlueprint of result.entities) {
    const entity = entityBlueprint.entity;
    const tableName = entity.LogicalName;

    if (isSystemEntity(tableName.toLowerCase())) {
      continue;
    }

    lines.push(`Table ${tableName} {`);

    const displayName = entity.DisplayName?.UserLocalizedLabel?.Label || tableName;
    lines.push(`  Note: '${displayName.replace(/'/g, "\\'")}'`);
    lines.push('');

    const attributes = entity.Attributes || [];

    if (attributes.length > 0) {
      // Full attribute data available — emit all columns.
      for (const attr of attributes) {
        const columnName = attr.LogicalName;
        const dataType = mapAttributeTypeToDbType(attr.AttributeType);
        const constraints: string[] = [];

        if (attr.IsPrimaryId) {
          constraints.push('pk');
        }
        if (attr.RequiredLevel?.Value === 'ApplicationRequired' || attr.RequiredLevel?.Value === 'SystemRequired') {
          constraints.push('not null');
        }
        const attrDisplayName = attr.DisplayName?.UserLocalizedLabel?.Label;
        if (attrDisplayName && attrDisplayName !== columnName) {
          constraints.push(`note: '${attrDisplayName.replace(/'/g, "\\'")}'`);
        }

        const constraintStr = constraints.length > 0 ? ` [${constraints.join(', ')}]` : '';
        lines.push(`  ${columnName} ${dataType}${constraintStr}`);
      }
    } else {
      const relCols = relationshipColumns.get(tableName.toLowerCase());
      if (relCols && relCols.size > 0) {
        // No attribute data but relationship columns are known — emit those so
        // Ref lines reference valid columns.
        for (const col of relCols) {
          lines.push(`  ${col} uniqueidentifier`);
        }
      } else {
        // No attribute or relationship data at all — safety-net placeholder.
        lines.push(`  id uniqueidentifier [note: 'Attribute data not available']`);
      }
    }

    lines.push('}');
    lines.push('');
  }

  // ── Pass 4: generate Ref lines ───────────────────────────────────────────
  lines.push('// Relationships');
  lines.push('');

  // Helper: returns the effective column set for an entity (real attributes
  // take priority; relationship-derived columns used as fallback).
  const getEntityCols = (name: string): Set<string> | undefined =>
    entityAttributes.get(name) ?? relationshipColumns.get(name);

  for (const entityBlueprint of result.entities) {
    const entity = entityBlueprint.entity;

    // Many-to-One relationships
    for (const rel of entity.ManyToOneRelationships || []) {
      if (isSystemRelationship(rel.SchemaName, rel.ReferencingAttribute, rel.ReferencedEntity, rel.ReferencingEntity)) {
        continue;
      }
      if (!exportedEntities.has(rel.ReferencingEntity.toLowerCase()) ||
          !exportedEntities.has(rel.ReferencedEntity.toLowerCase())) {
        continue;
      }

      // Only validate when column data is available; if no data exists for an
      // entity the relationship is still emitted (better to show than omit).
      const referencingCols = getEntityCols(rel.ReferencingEntity.toLowerCase());
      const referencedCols  = getEntityCols(rel.ReferencedEntity.toLowerCase());
      if (referencingCols && !referencingCols.has(rel.ReferencingAttribute.toLowerCase())) {
        continue;
      }
      if (referencedCols && !referencedCols.has(rel.ReferencedAttribute.toLowerCase())) {
        continue;
      }

      const relKey = `${rel.ReferencingEntity}.${rel.ReferencingAttribute}->${rel.ReferencedEntity}.${rel.ReferencedAttribute}`;
      if (!processedRelationships.has(relKey)) {
        processedRelationships.add(relKey);
        lines.push(`Ref: ${rel.ReferencingEntity}.${rel.ReferencingAttribute} > ${rel.ReferencedEntity}.${rel.ReferencedAttribute}`);
      }
    }

    // Many-to-Many relationships — documented as comments
    for (const rel of entity.ManyToManyRelationships || []) {
      if (isSystemRelationship(rel.SchemaName, undefined, rel.Entity1LogicalName, rel.Entity2LogicalName)) {
        continue;
      }
      if (!exportedEntities.has(rel.Entity1LogicalName.toLowerCase()) ||
          !exportedEntities.has(rel.Entity2LogicalName.toLowerCase())) {
        continue;
      }

      const entities = [rel.Entity1LogicalName, rel.Entity2LogicalName].sort();
      const relKey = `${entities[0]}<>${entities[1]}:${rel.IntersectEntityName}`;
      if (!processedRelationships.has(relKey)) {
        processedRelationships.add(relKey);
        lines.push(`// M:N: ${rel.Entity1LogicalName} <> ${rel.Entity2LogicalName} (via ${rel.IntersectEntityName})`);
      }
    }
  }

  return lines.join('\n');
}

/**
 * Maps Dataverse attribute types to database column types for dbdiagram.io
 */
function mapAttributeTypeToDbType(attributeType: string): string {
  const typeMap: Record<string, string> = {
    'String': 'nvarchar',
    'Memo': 'nvarchar(max)',
    'Integer': 'int',
    'BigInt': 'bigint',
    'Decimal': 'decimal',
    'Double': 'float',
    'Money': 'money',
    'Boolean': 'bit',
    'DateTime': 'datetime',
    'Lookup': 'uniqueidentifier',
    'Customer': 'uniqueidentifier',
    'Owner': 'uniqueidentifier',
    'Uniqueidentifier': 'uniqueidentifier',
    'Picklist': 'int',
    'State': 'int',
    'Status': 'int',
    'Virtual': 'nvarchar',
    'EntityName': 'nvarchar',
    'ManagedProperty': 'bit',
  };

  return typeMap[attributeType] || 'nvarchar';
}
